### ISSUE TITLE
Time Adjustment

### ISSUE THREAD

**Issue by giittyy** [mysticcoders/voicenotes-sync#30] opened 2024-07-03 01:50 UTC
Please add an option to put what time zone we are currently in and then adjust the time zone in the meta data and the date prepended in the title accordingly. 

Currently Dates are way off because the date is based off 0 time zone.

**Comment by yoghurtdewdew** [comment] 2024-08-14 10:12
Wrong time zone in yaml now. Wish same like in voicenotes app.

**Comment by giittyy** [comment] 2024-08-14 17:51
Voicenotes also has the wrong timezone though. Honestly that's the bigger issue, but I'll take it if at least its correct in obsidian.

**Comment by kinabalu** [comment] 2024-08-14 18:36
so we're talking about 0.20.0-beta has the wrong timezone?

**Comment by giittyy** [comment] 2024-08-14 19:18
Yes

**Comment by giittyy** [comment] 2024-08-14 19:21
Yes it's for the beta, but it's only the front matter properties. They're based off 0 time zone instead of switching to local. In the new beta the  date which can be used for title and body switches to the local time zone. The best solution would probably be to just open up the front matter in the same way the body of the note is able to be customized now.

**Comment by yoghurtdewdew** [comment] 2024-08-19 10:01
I would like to use another obsidian plugin, project, at the same time. I hope I can put my notes on the calendar view through the application of project, so that I can see which notes were created on each date. But at present, the property is text and wrong time zone. After I changed the property of text  to date&time, it still cannot be recognized in project. Hope supporting!

**Comment by yoghurtdewdew** [comment] 2024-08-20 02:44
![Screenshot_20240820_104058.jpg](https://github.com/user-attachments/assets/18a7df72-d446-47e1-91f5-2801777ce75a)

I remember the saying that this APP voicenotes has originally wrong time zone?
But I found that my time zone here is normal. All at the right time, a little difference just from an edit operation after it created.

**Comment by hjamet** [comment] 2024-08-20 07:04
Hello [yoghurtdewdew](https://github.com/yoghurtdewdew)!

I'm sorry, I can't reproduce the bug on my end: the dates are in the correct timezone :/

As for the use of the calendar plugin, I don't know which one you're using and it's therefore difficult for me to help. The next update (https://github.com/mysticcoders/voicenotes-sync/pull/42) should add the ability to modify the frontmatter while customizing the date format, which should solve your problem! :)

**Comment by yoghurtdewdew** [comment] 2024-08-20 12:59
@hjamet Thank you very much for your reply! Maybe I didn't express myself clearly enough. 

I mean, there is no problem with the timestamp in the voicenotes APP itself. But when this note was synchronized to my obsidian, its time was wrong. 
The time problem mainly lies in the wrong time zone. For example, the picture in my screenshot above is the thread of a note, its parent notes are created at 10:10. But when it was synchronized to obsidian, its creation time became 2:10, a difference of eight hours. It shows that there is an error in the time zone, local time zone or manually setting needed.

<img width="363" alt="image" src="https://github.com/user-attachments/assets/35ccf7d8-bdd5-43ab-812d-93ec19fd1acb">

You can see that I changed the property from text to date & time. But when I created project using project plugin 
 obsidian://show-plugin?id=obsidian-projects , I found that its property was still text, not the date & time that I needed, which could not be showed in the calendar view(plugin is still project).

<img width="465" alt="image" src="https://github.com/user-attachments/assets/1e3c9b6f-a7f3-4116-8016-3fbf8f9d523d">

**Comment by giittyy** [comment] 2024-08-20 17:40
Correct, so when they change the ability to edit frontmatter you will be able to put it into a time format your other plugin can read. 

In regards to the app. I said that it was wrong because it was going off 0 time zone for a long time in the app. It no longer does that. 

Thanks for your continued work on this

**Comment by yoghurtdewdew** [comment] 2024-08-27 03:09
I updated this plugin and found that all time property of notes became `00:00`.

<img width="361" alt="image" src="https://github.com/user-attachments/assets/34a2aef3-e907-41b2-b670-1db2119792a0">

**Comment by kinabalu** [comment] 2024-08-27 13:32
what is the value in your settings for `dateFormat`?

**Comment by yoghurtdewdew** [comment] 2024-08-28 14:54
@kinabalu Thanks for your pointing out for this! Now time would show in property.

**Comment by kinabalu** [comment] 2024-12-04 03:24
reading through this and latest, this is fixed now in 0.0.30 when the edit frontmatter gets committed.

**Closed by kinabalu** 2024-12-04 03:24 UTC
